### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MarcGodard** [feathersjs/can-connect-feathers#7]
All I get is errors!

```
Potentially unhandled rejection [7] SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Object.eval (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/can-connect-feathers/src/can-connect-feathers.js!eval:155:46)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at Object.<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3373:41)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at done (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:8759:14)
    at .<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:9123:9)
    at onload (/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/done-ssr/lib/zones/xhr.js:21:20)
Potentially unhandled rejection [8] SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Object.eval (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/can-connect-feathers/src/can-connect-feathers.js!eval:155:46)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at Object.<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3373:41)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at done (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:8759:14)
    at .<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:9123:9)
    at onload (/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/done-ssr/lib/zones/xhr.js:21:20)
```

Also you should add http://semantic-ui.com/ to the frameworks

**Comment by MarcGodard** [comment]
Opps Wrong github repo... my bad...
